export const songConstants = {
    START_LOADING: 'START_LOADING',
    STOP_LOADING: 'STOP_LOADING',
    GETSONG_SUCCESS: 'GETSONG_SUCCESS',
    GETSONG_FAILED: 'GETSONG_FAILED',
    CREATESONG_SUCCESS: 'CREATESONG_SUCCESS',
    CREATESONG_FAILED: 'CREATESONG_FAILED',
    GET_SONG_BYID_SUCCESS: 'GET_SONG_BYID_SUCCESS',
    GET_SONG_BYID_FAILED: 'GET_SONG_BYID_FAILED'
};
